indent-width = 4
line-length = 99
target-version = "py311"
output-format = "concise"
required-version = ">=0.16.7"

exclude = [
    ".git",
    ".venv",
    "build",
    "dist",
    "tools/*",
]

[format]
docstring-code-format = true
docstring-code-line-length = 99
indent-style = "space"
line-ending = "lf"
quote-style = "double"

[lint]
preview = true
select = ["ALL"]

ignore = [
  "incorrect-blank-line-before-class",    # incorrect-blank-line-before-class
  "multi-line-summary-second-line",    # multi-line-summary-second-line
  "magic-value-comparison", # magic-value-comparison
  "assert",    # assert
  "missing-trailing-comma",  # missing-trailing-comma
]

[lint.flake8-copyright]
notice-rgx = "(?m)^# SPDX-FileCopyrightText: Aresys S\\.r\\.l\\. <info@aresys\\.it>\\r?\\n# SPDX-License-Identifier: MIT\\r?$"

[lint.per-file-ignores]
"**/__init__.py" = ["undefined-local-with-import-star"] # undefined-local-with-import-star
"scripts/**/*.py" = [
  "implicit-namespace-package", # implicit-namespace-package
  "suspicious-xml-element-tree-usage",   # suspicious-xml-element-tree-usage
  "suspicious-subprocess-import",   # suspicious-subprocess-import
  "suspicious-xml-etree-import",   # suspicious-xml-etree-import
  "subprocess-without-shell-equals-true",   # subprocess-without-shell-equals-true
  "start-process-with-partial-path",   # start-process-with-partial-path
]
"src/aresys_io/sarsystem/**/*.py" = ["eq-without-hash"] # eq-without-hash
"tests/**/*.py" = [
  "D",       # all pydocstyle docstring rules
  "compare-to-empty-string", # compare-to-empty-string
  "private-member-access",  # private-member-access
]
"src/aresys_io/**/models/*.py" = [
  "D",    # all pydocstyle docstring rules
  "line-too-long", # line-too-long
]

[lint.pydoclint]
ignore-one-line-docstrings = true # one-line-docstring

[lint.pydocstyle]
convention = "numpy"
ignore-var-parameters = true # var-parameter-names-in-docstrings

[lint.pylint]
max-public-methods = 23 # too-many-public-methods
