<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="PointTargets">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="TargetType">
					<xs:annotation>
						<xs:documentation>0: LLH, 1: ECEF, 2: Normalized</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:enumeration value="0"/>
							<xs:enumeration value="1"/>
							<xs:enumeration value="2"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Target" type="TargetTagType" maxOccurs="unbounded"/>
				<xs:element name="Ntarget" type="xs:int"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="RCSType">
		<xs:sequence>
			<xs:element name="val" type="valTypeComplex" minOccurs="2" maxOccurs="2"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TargetTagType">
		<xs:sequence>
			<xs:element name="Coord">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="val" type="valType" minOccurs="3" maxOccurs="3"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="RCS_H" type="RCSType"/>
			<xs:element name="RCS_V" type="RCSType"/>
			<xs:element name="Delay">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="val" type="valType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Number" type="xs:int" use="required"/>
	</xs:complexType>
	<xs:complexType name="valType">
		<xs:simpleContent>
			<xs:extension base="xs:float">
				<xs:attribute name="N" type="xs:int" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="valTypeComplex">
		<xs:sequence>
			<xs:element name="re" type="xs:float"/>
			<xs:element name="im" type="xs:float"/>
		</xs:sequence>
		<xs:attribute name="N" type="xs:int" use="required"/>
	</xs:complexType>
</xs:schema>